### ISSUE TITLE
这个要怎么部署呢？

### ISSUE THREAD

**Issue by voodooq** [IceSeaOnly/huobi#3]
请大概写一下

**Comment by IceSeaOnly** [comment]
首先在common/src/main/resources/下创建一个authentication.properties文件，内容如下：

auth.accessKeyId=你在火币pro申请的accessKeyId
auth.accessKeySecret=你在火币pro申请的accessKeySecret
auth.assetPassword=null

mns.serverHead=选填，你的应用地址，勿以/结尾，如http://baidu.com
mns.accountendpoint=选填，阿里云的消息队列接入accountendpoint
mns.accesskeyid=选填，阿里云的消息队列接入accesskeyid
mns.accesskeysecret=选填，阿里云的消息队列接入accesskeysecret
mns.queueName=选填，阿里云的消息队列接入queueName
mns.phone=选填，短信报警人手机号
mns.tpl=选填，阿里大于短信模板号，如SMS_123456789
mns.wxTpl=选填，日常水位高低值，微信模板消息OPENTM207589525
mns.wxWaterMonitorTpl=选填，水位监控通知，微信模板消息OPENTM414876002
mns.wxEmergenceNewsTpl=选填，紧急事件通知，微信模板消息OPENTM206019251


然后mvn打包，运行web模块下生成的jar应用即可;
数据库自动映射数据表，admin表中添加一个username为admin，password为e10adc3949ba59abbe56e057f20f883e的账号，即可使用admin+123456的账号登录;

与微信关联的功能可以微信搜索公众号“**小骨头校园服务**”，点击“发现资源”功能栏体验，感谢关注，个人项目多有不足，敬请谅解;

**Comment by IceSeaOnly** [comment]
忘了说了，通过阿里云消息队列发出的所有消息都会在我另一个应用中消费，其实很简单，就是把消息通过微信模板消息或短信发出，并没有其他功能，代码就不贴了。
